name: TEST

on:
  repository_dispatch:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/test.yml'

env:
  FOLDER: test
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  FEEDS: feeds.conf.default
  CONFIG: menuconfig
  SETTINGS: default.settings
  DIYSH1: diy1.sh
  DIYSH2: testscript.sh  
  SSH_ACTIONS: true
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_COWTRANSFER: false
  UPLOAD_WETRANSFER: false
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir
        
    - name: Clone source code
      working-directory: /workdir
      run: |
        mkdir -p openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt

    - name: Load custom feeds, run diy1.sh, update packages, and install packages
      run: |
        [ -e $FOLDER/$CONFIG ] && mv $FOLDER/$CONFIG openwrt/.config && ls -al openwrt/.config
        chmod +x $FOLDER/$DIYSH2
        echo '==============================='
        echo $FOLDER/$DIYSH2
        echo '==============================='
        cd openwrt
        $GITHUB_WORKSPACE/$FOLDER/$DIYSH2
        echo '==============================='
        echo script ended!
        echo '==============================='
        # 在 Debian 中安装 qemu-utils
        #sudo apt install qemu-utils
        # 转换 img 为 vhdx, 其中 subformat 可为 "dynamic" 或 "fixed"
        #qemu-img convert -f raw -O vhdx -o subformat=dynamic input.img output.vhdx
            
    - name: SSH connection to Actions
      uses: aaronbagot/OWRT_build_ssh@master
      if: env.SSH_ACTIONS == 'true' || contains(github.event.action, 'ssh')
